### ISSUE TITLE
AADSTS7000222: The provided client secret keys are expired.

### ISSUE THREAD

**Issue by Epiccode887** [Azure-Samples/active-directory-dotnetcore-daemon-v2#87] opened 2020-08-19 07:10 UTC
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [ x ] bug report -> please search issues before submitting
- [ ] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
> Register Azure AD app using Configure.ps1 script and immediately run the application that will use the client secret of newly registered app and acquire access token. 

### Any log messages given by the failure
> 
 ```
Caused by: com.microsoft.aad.msal4j.MsalServiceException: AADSTS7000222: The provided client secret keys are expired. Visit the Azure Portal to create new keys for your app, or consider using certificate credentials for added security: https://docs.microsoft.com/azure/active-directory/develop/active-directory-certificate-credentials
Trace ID: 7fcf7cbe-ce35-44fa-93f8-b2c7b6221d00
Correlation ID: b1ea1fd6-59c2-4cb7-9baa-eecae5452848
Timestamp: 2020-08-18 11:19:27Z
```

### Expected/desired behavior
> As the app is newly registered and the client secret key is also valid, no such error should be thrown.

### OS and Version?
> Windows 2016

### Versions
>

### Mention any other details that might be useful

Below app manifest gets generated after app registration. We have modified the script to generate client secret key which is valid for a duration of 5 years.

```
"passwordCredentials": [
        {
            "customKeyIdentifier": null,
            "endDate": "2025-08-18T18:16:34.5569146Z",
            "keyId": "58f9fbad-1732-4d65-9d40-428891bbXXXX",
            "startDate": "2020-08-18T18:16:34.5569146Z",
            "value": null,
            "createdOn": null,
            "hint": null,
            "displayName": null
        }
    ],

```
The timestamp seen in the error log is **_2020-08-18 11:19:27Z_** and password credentials start date(as seen in app manifest) is "**_2020-08-18T18:16:34.5569146Z_**".
Additionally, app created date is **_"createdDateTime": "2020-08-18T11:16:35Z"_** in the app manifest.

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by jmprieur** [comment] 2020-08-19 10:33
@Epiccode887 : If you are using .NET Core did you, by chance use user secrests (right click on the project | manage user secrets)? If you are using user secrets they have precedence over the secret in the appsettings.json, which could explain what you are seeing

On the side note, are you sure that you raised this issue on the right repo?
I mean this is a dotnet daemon, and the exception seems to be a Java one: Caused by: com.microsoft.aad.msal4j.MsalServiceException

**Comment by Epiccode887** [comment] 2020-08-19 10:56
@jmprieur : Yes, I'm using MSAL Java library. But I had referred to the app creation script from this repository hence raised a query here.
Also, could you please provide more details on user secrets ? Are you referring to the .NET code?

**Comment by jmprieur** [comment] 2020-08-19 11:38
Yes @Epiccode887:  this is for .NET core: https://docs.microsoft.com/en-us/aspnet/core/security/app-secrets?view=aspnetcore-3.1&tabs=windows

You might want to raise an issue on MSAL.Java ?

**Comment by Epiccode887** [comment] 2020-08-19 12:47
@jmprieur : Yes, I can raise a issue on MSAL Java but I had few queries related to the app creation script:
1) Could you please let me know what time/timezone is considered while executing the below command:
    **_$fromDate = [DateTime]::Now;_**
2) Also could you please let me know, in which timezone the app gets created on Azure AD portal once you run the app creation script?
3) Which time/timezone the password credentials get created on the portal?

**Comment by jmprieur** [comment] 2020-08-19 14:45
@Epiccode887 : I guess this is the time zone of your PowerShell host/console. I'm not sure for Azure AD.
@lnalepa would you know?

**Comment by Epiccode887** [comment] 2020-08-26 08:08
@jmprieur,  @lnalepa Do we have any updates on the above query? Can someone help me out here as this is impacting our time-bound release.

**Comment by jmprieur** [comment] 2020-08-26 08:13
@hpsin would you have an idea?

**Comment by jmprieur** [comment] 2020-10-19 10:28
Closing as there was no answer

**Closed by jmprieur** 2020-10-19 10:28 UTC
Labels: question
