### ISSUE TITLE
AppCreationScript failed

### ISSUE THREAD

**Issue by 3pillardeveloper** [Azure-Samples/active-directory-dotnetcore-daemon-v2#154] opened 2023-03-24 17:58 UTC
### This issue is for a: (mark with an `x`)
```
- [x ] bug report -> please search issues before submitting
- [ ] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
>

In Powershell run as admin:
```
Install-Module AzureAD
```

In Powershell:
```ps1
Set-ExecutionPolicy -ExecutionPolicy Bypass -Scope Process
.\Configure.ps
```

### Any log messages given by the failure
>

```
Connect-AzureAD: C:\Users\REDACTED\source\repos\active-directory-dotnetcore-daemon-v2-master\2-Call-OwnApi\AppCreationScripts\Configure.ps1:144
Line |
 144 |              $creds = Connect-AzureAD -Credential $Credential
     |                       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | One or more errors occurred. (Could not load type 'System.Security.Cryptography.SHA256Cng' from assembly 'System.Core, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'.): Could not load type 'System.Security.Cryptography.SHA256Cng' from assembly
     | 'System.Core, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'.
```

### Expected/desired behavior
>

The app creation scripts succeeds in post-login behavior.

### OS and Version?
> Windows 7, 8 or 10. Linux (which distribution). macOS (Yosemite? El Capitan? Sierra?)

Windows 10

### Versions
>

- AzureAD 2.0.2.140

### Mention any other details that might be useful

N/A

**Comment by jennyf19** [comment] 2023-03-24 18:14
FYI @jmprieur

**Comment by jmprieur** [comment] 2023-04-02 21:49
@derisen @v-michaelmi are you aware of this:
https://github.com/PowerShell/PowerShell/issues/10473#issuecomment-1487180153?

**Comment by derisen** [comment] 2023-04-03 17:34
@jmprieur we've already migrated to Graph PS SDK, but didn't had the chance to regenerate the scripts here cc @v-michaelmi

**Comment by v-michaelmi** [comment] 2023-04-03 19:29
Updated the scripts here:

https://github.com/Azure-Samples/active-directory-dotnetcore-daemon-v2/pull/156

May need to sync up if certificate setup automation is required as well.

**Comment by donrolling** [comment] 2023-04-07 20:01
This script fails for me too. Pretty frustrating because this is the best tutorial that I've found, but I haven't been able to get it working.

**Comment by jmprieur** [comment] 2023-04-07 21:00
@donrolling : it's still failing after the update?
Can you pull the latest, and if it fails, share the error you get?

**Comment by donrolling** [comment] 2023-04-07 21:43
I pulled it earlier today and there have been no changes on the main branch.

Here is my error:

Connecting to Microsoft Graph
Welcome To Microsoft Graph!
Get-MgUser_List1:
C:\Projects\active-directory-dotnetcore-daemon-v2\2-Call-OwnApi\AppCreationScripts\Configure.ps1:250:57
Line |
 250 |  … ser = Get-MgUser -Filter "UserPrincipalName eq
'$($context.Account)'"
     |                                                      ~~~~~~~~~~~~~~~~
     | Exception of type
'Microsoft.Fast.Profile.Core.Exception.ProfileAccessDeniedException' was
thrown.
Get-MgOrganization_List1:
C:\Projects\active-directory-dotnetcore-daemon-v2\2-Call-OwnApi\AppCreationScripts\Configure.ps1:253:5
Line |
 253 |      $Tenant = Get-MgOrganization
     |      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | Unable to find target address
Connected to Tenant  () as account ''. Domain is ''
Creating the AAD application (TodoList-webapi-daemon-v2)
New-MgServicePrincipal_CreateExpanded1:
C:\Projects\active-directory-dotnetcore-daemon-v2\2-Call-OwnApi\AppCreationScripts\Configure.ps1:284:5
Line |
 284 |      $serviceServicePrincipal = New-MgServicePrincipal -AppId
$current …
     |
 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | Unable to find target address
Get-MgApplicationOwner_List:
C:\Projects\active-directory-dotnetcore-daemon-v2\2-Call-OwnApi\AppCreationScripts\Configure.ps1:287:5
Line |
 287 |      $owner = Get-MgApplicationOwner -ApplicationId
$currentAppObjectI …
     |
 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | Resource not found.
System.Management.Automation.ParameterBindingArgumentTransformationException:
Cannot process argument transformation on parameter 'BodyParameter'. Cannot
convert the "=" value of type "System.String" to type
"Microsoft.Graph.PowerShell.Models.IReferenceCreate".
 ---> System.Management.Automation.ArgumentTransformationMetadataException:
Cannot convert the "=" value of type "System.String" to type
"Microsoft.Graph.PowerShell.Models.IReferenceCreate".
 ---> System.Management.Automation.PSInvalidCastException: Cannot convert
the "=" value of type "System.String" to type
"Microsoft.Graph.PowerShell.Models.IReferenceCreate".
   at
System.Management.Automation.LanguagePrimitives.ConvertCheckingForCustomConverter.Convert(Object
valueToConvert, Type resultType, Boolean recursion, PSObject
originalValueToConvert, IFormatProvider formatProvider, TypeTable
backupTable)
   at
System.Management.Automation.LanguagePrimitives.ConversionData`1.Invoke(Object
valueToConvert, Type resultType, Boolean recurse, PSObject
originalValueToConvert, IFormatProvider formatProvider, TypeTable
backupTable)
   at System.Management.Automation.LanguagePrimitives.ConvertTo(Object
valueToConvert, Type resultType, Boolean recursion, IFormatProvider
formatProvider, TypeTable backupTypeTable)
   at
System.Management.Automation.ArgumentTypeConverterAttribute.Transform(EngineIntrinsics
engineIntrinsics, Object inputData, Boolean bindingParameters, Boolean
bindingScriptCmdlet)
   --- End of inner exception stack trace ---
   at
System.Management.Automation.ArgumentTypeConverterAttribute.Transform(EngineIntrinsics
engineIntrinsics, Object inputData, Boolean bindingParameters, Boolean
bindingScriptCmdlet)
   at
System.Management.Automation.ParameterBinderBase.BindParameter(CommandParameterInternal
parameter, CompiledCommandParameter parameterMetadata,
ParameterBindingFlags flags)
   --- End of inner exception stack trace ---
   at
System.Management.Automation.ExceptionHandlingOps.CheckActionPreference(FunctionContext
funcContext, Exception exception)
   at
System.Management.Automation.Interpreter.ActionCallInstruction`2.Run(InterpretedFrame
frame)
   at
System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame
frame)
   at
System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame
frame)
WARNING: Cannot process argument transformation on parameter
'BodyParameter'. Cannot convert the "=" value of type "System.String" to
type "Microsoft.Graph.PowerShell.Models.IReferenceCreate".
Unable to register apps. Error is Cannot process argument transformation on
parameter 'BodyParameter'. Cannot convert the "=" value of type
"System.String" to type
"Microsoft.Graph.PowerShell.Models.IReferenceCreate"..
Disconnecting from tenant

**Comment by jmprieur** [comment] 2023-04-07 21:45
Are you an admin of the tenant? or at least an application admin?

**Comment by donrolling** [comment] 2023-04-07 22:17
I am the admin, yes

**Comment by jmprieur** [comment] 2023-04-07 22:59
@donrolling.
I just tested it.

1. I've used the **PowerShell** command line console (not Windows PowerShell)
2. I've run from `C:\ghs\active-directory-dotnetcore-daemon-v2\2-Call-OwnApi\AppCreationScripts` the command `.\Configure.ps1  -TenantId jmprieurhotmail.onmicrosoft.com`. (The first time it will install the Graph Powershell packages), you'll get the consent screen:

![image](https://user-images.githubusercontent.com/13203188/230690007-d1dd7ea3-76de-45a7-9715-bb2cb320a5bf.png)

@v-michaelmi @derisen 
I got this error:
![image](https://user-images.githubusercontent.com/13203188/230690096-59e60487-748c-431c-9256-7c45b7828a04.png)

**Comment by v-michaelmi** [comment] 2023-04-10 18:09
@jmprieur @donrolling 

I just re-ran a fresh clone on my machine and didn't have any issues but I am able to reproduce this issue if the **$context.Account** value is empty.

Seems to work fine on **PowerShell 7.3.3** but I'll try and get a hard diagnosis for what exactly is going on here...

**Comment by jmprieur** [comment] 2023-04-10 18:10
Thanks @v-michaelmi

**Comment by v-michaelmi** [comment] 2023-04-10 19:46
Unfortunately I'm still unable to reproduce on my end. Would you be able to share the version of PowerShell you're currently using?

What seems to be happening is either the **Connect-MgGraph** command is not successfully executing or the permissions for the PowerShell application are not being configured correctly.

If everything is installed and configured correctly you should be able to run 

``` powershell
PS C:\> Connect-MgGraph
Welcome To Microsoft Graph!
PS C:\> Get-MgContext
ClientId              : CLIENT_ID
TenantId              : TENANT_ID
CertificateThumbprint : 
Scopes                : {openid, profile, User.Read, email}
AuthType              : Delegated
AuthProviderType      : InteractiveAuthenticationProvider
CertificateName       : 
Account               : ACCOUNT_INFO
AppName               : Microsoft Graph PowerShell
ContextScope          : CurrentUser
Certificate           : 
PSHostVersion         : 7.3.3
```

**Connect-MgGraph** should launch a browser prompting for a login.

If the connection isn't established properly the **Get-MgContext** returns an empty object which seems to be what's happening here.

```Powershell
PS C:\> Get-MgContext     
PS C:\> 
```

It might worth trying to delete the **Microsoft Graph PowerShell** application found in the **Enterprise applications** section of **Azure Active Directory** on your tenant. You can delete it by navigating to the application, clicking **Properties** in the left blade then clicking **Delete**. Then try running on the scripts again and granting permissions to the application when the consent screen appears (you don't need to consent on behalf of the organization).

**Comment by jmprieur** [comment] 2023-04-10 20:14
I'm using 7.3.3

**Comment by v-michaelmi** [comment] 2023-04-11 17:27
@jmprieur @donrolling 

Checking in here. Were you guys able to run the **Connect-MgGraph** and **Get-MgContext** commands successfully?

If so, you should be able to run the scripts without any issue but if you can and the scripts still don't work please let me know!

**Comment by jmprieur** [comment] 2023-04-11 17:29
@v-michaelmi I just thought of something. I was using an MSA account. were you as well? or were you using an AAD account?

**Comment by v-michaelmi** [comment] 2023-04-11 17:30
@jmprieur  I was using an AAD account from a dummy tenant

**Comment by donrolling** [comment] 2023-04-11 18:11
I got the command to work, but it is definitely an AAD account. I didn't
get as much info back as you did.

**Comment by v-michaelmi** [comment] 2023-04-11 19:07
@donrolling and the script still doesn't work?

Can you share what fields are populated?

**Comment by donrolling** [comment] 2023-04-11 21:45
Script still doesn't work. Maybe it an issue with my Login. I have two
tenants (?) setup under my name. Not really sure why, probably from
things I setup a long time ago. One of these has a Free Trial on it and the
other one does not. Not sure how to deal with that though.

*Script Error:* Unable to register apps. Error is Cannot process argument
transformation on parameter 'BodyParameter'. Cannot convert the "=" value
of type "System.String" to type
"Microsoft.Graph.PowerShell.Models.IReferenceCreate"..

[image: image.png]

**Comment by v-michaelmi** [comment] 2023-04-12 01:28
@donrolling 

It's a good thing you did!

Based on your new error I caught a very old syntax bug that's been missed for some time.

Based on what I'm seeing here it looks like **Get-MgApplicationOwner** was failing which triggered a manual update that wasn't working correctly.

PR is [here](https://github.com/Azure-Samples/active-directory-dotnetcore-daemon-v2/pull/157/files) and the branch itself is [here](https://github.com/Azure-Samples/active-directory-dotnetcore-daemon-v2/tree/script-fix) if you want to give that a try.

**Comment by donrolling** [comment] 2023-04-12 03:10
Glad I could help. I'm sure others have had issues, but maybe didn't report
it and that's why nobody knew about it.

Thanks for working on this!

**Comment by v-michaelmi** [comment] 2023-04-12 16:50
@donrolling 

No worries, and definitely appreciate the catch!

Let me know if that resolved everything and I'll close this issue out.

**Comment by v-michaelmi** [comment] 2023-04-18 17:41
Closing this issue.

Please re-open if it still persists.

**Closed by v-michaelmi** 2023-04-18 17:41 UTC
Labels: AppCreationScript
